### PR TITLE
Remove deprecated api from galactic

### PR DESCRIPTION
**Pull request by wep21**
Remove deprecated api for `declare_parameter` from `galactic` to suppress build warnings.

### CODE REVIEW

**Comment by wep21** [comment]
@JWhitleyWork Could you review this?

**Comment by JWhitleyWork** [comment]
Since Galactic was only [just released today](https://discourse.ros.org/t/ros-2-galactic-geochelone-released/20559) and [isn't yet supported in `ros-tooling` CI jobs](https://github.com/ros-tooling/setup-ros/pull/388), I'd like to hold this until that is complete.

**Comment by wep21** [comment]
@JWhitleyWork I think these changes cause a build error on foxy, could you create `galactic` branch?

**Comment by JWhitleyWork** [comment]
@wep21 Please rebase your branch on `main` and you should get an updated Github Actions config file which will only runn for `galactic` and `rolling` on that branch.

**Comment by JWhitleyWork** [comment]
Nevermind. I applied the rebase. Once CI passess, I'll merge this and release for Galactic and Rolling.

**Pull request merged**
